config/routes.rb
Artisania::Application.routes.draw do

  root :to => "projects#index"

  resources :palettes do
    member do
      get :alt_show
    end
  end
  
  resources :attribute_layers
  resources :attributes
  resources :design_versions
  resources :product_categories
  resources :catalogs

  devise_for :users

  resources :projects do
    member do
      get  :design
      post :send_invitation
      get  :duplicate
    end
    collection do
      get :products_by_category
      get :products_by_artisan
      get :products
      get :customer_projects
      get :show_product_in_catalog

    end
  end

end

app/models/palette.rb
class Palette < ActiveRecord::Base
  
  attr_accessible :name, :project_id, :user_id, :attribute_layers_attributes

  validates :name, :presence  => true

  belongs_to :project

  has_one  :product_category

  has_many :attribute_layers
  
  # has_many :palette_attributes, :through => :attribute_layers
  accepts_nested_attributes_for :attribute_layers

end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  # GET /palettes
  # GET /palettes.json
  def index
    @palettes = Palette.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @palettes }
    end
  end

  # GET /palettes/1
  # GET /palettes/1.json
  def show
    @palette = Palette.find(params[:id])
    @attribute_layers = @palette.attribute_layers
    @ids = @attribute_layers.map { |layer| layer.id }
    @attributes = Attribute.all.select {|attr| @ids.include?(attr.id) }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @palette }
    end
  end

  def alt_show
    @palette = Palette.find(params[:id])
    @attribute_layers = @palette.attribute_layers
    @ids = @attribute_layers.map { |layer| layer.id }
    @attributes = Attribute.all.select {|attr| @ids.include?(attr.id) }
    render 'alt_show'
  end


  # GET /palettes/new
  # GET /palettes/new.json
  def new
    @palette = Palette.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @palette }
    end
  end

  # GET /palettes/1/edit
  def edit
    @palette = Palette.find(params[:id])
    @al = @palette.attribute_layers.build
    @attribute = @al.palette_attributes.build
  end

  # POST /palettes
  # POST /palettes.json
  def create
    @palette = Palette.new(params[:palette])
      if @palette.save
        redirect_to new_attribute_layer_path
      else
       render action: "new" 
      end
  end

  # PUT /palettes/1
  # PUT /palettes/1.json
  def update
    @palette = Palette.find(params[:id])

    respond_to do |format|
      if @palette.update_attributes(params[:palette])
        format.html { redirect_to @palette, notice: 'Palette was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @palette.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palettes/1
  # DELETE /palettes/1.json
  def destroy
    @palette = Palette.find(params[:id])
    @palette.destroy

    respond_to do |format|
      format.html { redirect_to palettes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/palettes_helper.rb
module PalettesHelper
end

app/views/palettes/_attribute_layer_fields.html.erb
<%= f.input :name, label: "Attribute Layer Name" %>

<%= f.simple_fields_for :palette_attributes do |attr_form| %>
	<%= render 'palette_attribute_fields', f: attr_form %>
<% end %>

<div><%= link_to_add_fields "Add Attribute", f, :palette_attributes %></div><br>

app/views/palettes/_form.html.erb
<%= simple_form_for(@palette) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	  <%= f.input :name, label: "Palette Name" %>
	  
	  
      <div id="attr-layer-old">
          <%= f.simple_fields_for :attribute_layers do |al_form| %>
              <%= render 'attribute_layer_fields', f: al_form %>
          <% end %>
      </div>
	  
  </div>
  
  

  <div class="form-actions">
    <%= f.button :submit, "Save" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/palettes/_palette_attribute_fields.html.erb
  <div class="form-inputs">
      <%= f.input :name, label: "Attribute Name" %>
      <%= f.file_field :attr_img %>
  </div><br>

app/views/palettes/alt_show.html.erb
<p id="notice"><%= notice %></p>

      <div class="row span8 b-ordered" id="design">
        <div class="span6" id="pallete">
          <%= @palette.name %>

          <div class="menu_ bordered">

            <%= select_tag :palette, options_from_collection_for_select(@attribute_layers, :id, :name), include_blank: true, id: 'attr-layer-select' %>
    
              <% @attributes.each do |attribute| %>
              <%= image_tag attribute.attr_img.url(:thumb), class: "#{attribute.attribute_layer.id} attr_" %>
              <% end %>

          </div>
        </div>
      </div>

<style>
#canvas_container_ {
    min-height: 700px;
    border: inherit;
    width: 700px;
}
</style>

 <script>

    $("#attr-layer-select").on("change", function() {
        var self = $("#attr-layer-select");
        console.log("here");
        console.log(this.options[this.selectedIndex].value);
        var class_val = this.options[this.selectedIndex].value;
        var all_elements = $(".attr_");
        console.log(all_elements);
        all_elements.hide();
        var sel_elements = $("."+class_val);
        sel_elements.show();
        console.log(sel_elements);

    });

 </script>

app/views/palettes/edit.html.erb
<h3>Editing palette</h3>

<%= render 'form' %>

<%= link_to 'Show', @palette %> |
<%= link_to 'Back', palettes_path %>

app/views/palettes/index.html.erb
<h3>Listing Palettes <%#= current_user.name %> </h3>

<table class="projects-table table table-bordered table-striped table-hover" id="projects-index" style="width: 1000px;">
  <tr>
    <th>Palette Name</th>
    <th>Product Category</th>
    <th>Project</th>
    <th>Project ID</th>
    <th>Actions</th>
  </tr>
 
<% @palettes.each do |palette| %>
  <tr>
    <td><%= palette.name %></td>
    <td><%= palette.project.product_category.name %></td>
    <td><%= palette.project.name %></td>
    <td><%= palette.project.id %></td>
    <td><%= link_to 'Show', palette %></td>
    <td><%= link_to 'Edit', edit_palette_path(palette) %></td>
    <td><%= link_to 'Remove', palette, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Palette', new_palette_path %>

app/views/palettes/new.html.erb
<h1>New palette</h1>

<%= render 'form' %>

<%= link_to 'Back', palettes_path %>

app/views/palettes/show.html.erb
<p id="notice"><%= notice %></p>


<h3> <%= @palette.name %> </h3>
<%= link_to 'Alt View', alt_show_palette_path, params: {alt: true} %>

 </br>
<%= link_to 'Edit Palette', edit_palette_path(@palette) %> |
<%= link_to 'Back', palettes_path %>

</br> </br>
</br> </br>


<% @attribute_layers.each do |attribute_layer| %>

<h4 style="display: inline;"><%= attribute_layer.name %></h4>
<%= link_to 'Edit Layer', edit_attribute_layer_path(attribute_layer) %>

</br> </br>

<!-- <%= link_to 'Show', attribute_layer_path %> -->
<table class="table table-bordered table-striped table-hover" id="projects-index" style="width: 1000px;">
  <tr>
    <th>Attribute Name</th>
    <th>Attr img</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% attribute_layer.palette_attributes.each do |attribute| %>
  <tr>
    <td><%= attribute.name %></td>
    <td><%= image_tag attribute.attr_img.url(:thumb) %></td>
    <!-- <td><%= link_to 'Show', attribute %></td> -->
    <td><%= link_to 'Edit', edit_attribute_path(attribute) %></td>
    <td><%= link_to 'Destroy', attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<% end %>