config/routes.rb
Artisania::Application.routes.draw do

  root :to => "projects#index"

  resources :palettes do
    member do
      get :alt_show
    end
  end
  
  resources :attribute_layers
  resources :attributes
  resources :design_versions
  resources :product_categories
  resources :catalogs

  devise_for :users

  resources :projects do
    member do
      get  :design
      post :send_invitation
      get  :duplicate
    end
    collection do
      get :products_by_category
      get :products_by_artisan
      get :products
      get :customer_projects
      get :show_product_in_catalog

    end
  end

end

app/models/attribute_layer.rb
class AttributeLayer < ActiveRecord::Base

  attr_accessible :name, :palette_attributes_attributes

  belongs_to :palette
  
  has_many :palette_attributes, :class_name => 'Attribute'
  accepts_nested_attributes_for :palette_attributes, :reject_if => :all_blank, :allow_destroy => true
  
end

app/controllers/attribute_layers_controller.rb
class AttributeLayersController < ApplicationController
  # GET /attribute_layers
  # GET /attribute_layers.json
  def index
    @attribute_layers = AttributeLayer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attribute_layers }
    end
  end

  # GET /attribute_layers/1
  # GET /attribute_layers/1.json
  def show
    @attribute_layer = AttributeLayer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attribute_layer }
    end
  end

  # GET /attribute_layers/new
  # GET /attribute_layers/new.json
  def new
    @attribute_layer = AttributeLayer.new
    @attribute_layer.palette_attributes.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attribute_layer }
    end
  end

  # GET /attribute_layers/1/edit
  def edit
    @attribute_layer = AttributeLayer.find(params[:id])
    @attribute = @attribute_layer.palette_attributes.build
  end

  # POST /attribute_layers
  # POST /attribute_layers.json
  def create
    @attribute_layer = AttributeLayer.new(params[:attribute_layer])
    
    if @attribute_layer.save
      redirect_to new_attribute_path
    else
      render action: "new"
    end
  end

  # PUT /attribute_layers/1
  # PUT /attribute_layers/1.json
  def update
    @attribute_layer = AttributeLayer.find(params[:id])
      if @attribute_layer.update_attributes(params[:attribute_layer])
        redirect_to @attribute_layer, notice: 'Attribute layer was successfully updated.'
      else
         render action: "edit"
      end
  end

  # DELETE /attribute_layers/1
  # DELETE /attribute_layers/1.json
  def destroy
    @attribute_layer = AttributeLayer.find(params[:id])
    @attribute_layer.destroy

    respond_to do |format|
      format.html { redirect_to attribute_layers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attribute_layers_helper.rb
module AttributeLayersHelper
end

app/views/attribute_layers/_form.html.erb
<%= simple_form_for(@attribute_layer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	  <%= f.input :name, label: "Attribute Layer Name" %>
  </div>

  <%= f.simple_fields_for :palette_attributes do |builder| %>
    <%= render 'palette_attribute_fields', :f => builder %>
  <% end %>
<div><%= link_to_add_fields "Add Attribute", f, :palette_attributes %></div>


  <div class="form-actions">
    <%= f.button :submit, "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/attribute_layers/_palette_attribute_fields.html.erb
  <div class="form-inputs">
      <%= f.input :name, label: "Attribute Name" %>
      <%= f.file_field :attr_img %>
  </div><br>

app/views/attribute_layers/edit.html.erb
<h3>Edit Attribute Layer</h3>

<%= render 'form' %>

<%= link_to 'Show', @attribute_layer %> |
<%= link_to 'Back', attribute_layers_path %>

app/views/attribute_layers/index.html.erb
<h3>Listing Attribute Layers</h3>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @attribute_layers.each do |attribute_layer| %>
    <tr>
      <td><%= attribute_layer.name %></td>
      <td><%= link_to 'Show', attribute_layer %></td>
      <td><%= link_to 'Edit', edit_attribute_layer_path(attribute_layer) %></td>
      <td><%= link_to 'Destroy', attribute_layer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Attribute layer', new_attribute_layer_path %>

app/views/attribute_layers/new.html.erb
<h3>New Attribute Layer</h3>

<%= render 'form' %>

<%= link_to 'Back', attribute_layers_path %>

app/views/attribute_layers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @attribute_layer.name %>
</p>

<table>
  <tr>
    <th>Attribute Name</th>
    <th>Attr img</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attribute_layer.palette_attributes.each do |attribute| %>
  <tr>
    <td><%= attribute.name %></td>
    <td><%= image_tag attribute.attr_img.url(:thumb) %></td>
    <td><%= link_to 'Show', attribute %></td>
    <td><%= link_to 'Edit', edit_attribute_path(attribute) %></td>
    <td><%= link_to 'Destroy', attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_attribute_layer_path(@attribute_layer) %> |
<%= link_to 'Back', attribute_layers_path %>