config/routes.rb
Artisania::Application.routes.draw do

  root :to => "projects#index"

  resources :palettes do
    member do
      get :alt_show
    end
  end
  
  resources :attribute_layers
  resources :attributes
  resources :design_versions
  resources :product_categories
  resources :catalogs

  devise_for :users

  resources :projects do
    member do
      get  :design
      post :send_invitation
      get  :duplicate
    end
    collection do
      get :products_by_category
      get :products_by_artisan
      get :products
      get :customer_projects
      get :show_product_in_catalog

    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  attr_accessible :name, :description, :img_file, :product_category_id,
                  :show_in_catalog, :palettes_attributes, :customer_id
  has_attached_file :img_file, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  
  validates :name, :presence  => true

  has_many :palettes
  accepts_nested_attributes_for :palettes
  
  belongs_to :user
  belongs_to :product_category
  
  
  def customer
    user_id = self.customer_id
    if user_id
      User.find(user_id).email
    else
      " -- "
    end
  end


  def design_versions
    DesignVersion.where(project_id: self.id)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  before_filter :authenticate_user!
  def index
    if current_user.artisan?
      @projects = Project.where("user_id =?", current_user.id)
      render 'artisan_index'
    elsif current_user.customer?
      @projects = Project.where(customer_id: current_user.id)
      render 'customer_index'
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @palettes = Palette.where("project_id=?", @project.id)
    @proj_img = @project.img_file.url
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @palette = @project.palettes.build
    @al = @palette.attribute_layers.build
    @attribute = @al.palette_attributes.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.user = current_user

    if @project.save
      redirect_to project_path(@project)
    else
      render action: :edit, id: @project.id
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def send_invitation
    session[:return_to] = request.referer
    @project = Project.find(params[:id])
    if current_user.customer?
      ProjectMailer.send_invitation_for_project(@project, @project.user.email).deliver
    else
      ProjectMailer.send_invitation_for_project(@project, User.find(@project.customer_id).email).deliver if @project.customer_id
    end
    redirect_to session[:return_to]
  end


  def design
    @project = Project.find(params[:id])
    design_versions = DesignVersion.where("project_id=?", @project.id)
    most_rec_des_ver = design_versions.last
    if @project.parent_project_id
      palettes = Palette.where("project_id=?", @project.parent_project_id)
    else
      palettes = Palette.where("project_id=?", @project.id)
    end
    @attribute_layers = AttributeLayer.where("palette_id=?", palettes.first.id)
    @attributes = []
    @attribute_layers.each do |al|
      @attributes += Attribute.where("attribute_layer_id=?", al.id)
    end
    session[:project_id] = @project.id
    render 'design'
  end
  
  def products_by_category
    @projects = Project.where(product_category_id: params[:product_catgory_id], show_in_catalog: true)
  end
  
  def products_by_artisan
    @projects = Project.where(user_id: params[:user_id], show_in_catalog: true)
    render 'products'
  end
  
  def duplicate
    project = Project.find(params[:id])
    @project = project.amoeba_dup
    @project.update_attributes(customer_id: current_user.id, show_in_catalog: false)
    @project.parent_project_id = project.id
    @project.img_file = project.img_file
    @project.save

    design_versions = DesignVersion.where("project_id=?", project.id)
    design_versions.each do |dv|
      new_dv = dv.amoeba_dup
      new_dv.project_id = @project.id
      new_dv.save
    end
    
    redirect_to action: :show, id: @project.id
  end
  
  def products
    @projects = Project.where(show_in_catalog: true)
  end
  
  def customer_projects
    @projects = Project.where(customer_id: params[:customer_id])
  end

  def show_product_in_catalog
    project = Project.find(params[:id])
    project.show_in_catalog = false
    project.save
    redirect_to action: :products_by_artisan, user_id: current_user.id
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, url_path: projects_path, html: { multipart: true } do |f| %>

<ul id="main-tabs" class="nav nav-tabs">
  <li class="active"><a href="#project" data-toggle="tab">Project</a></li>
  <li><a href="#prod-category" data-toggle="tab">Category</a></li>
  <li><a href="#palette" data-toggle="tab">Palette</a></li>
  <li><a href="#attr-layer" id="_atr_" data-toggle="tab">Attribute Layer</a></li>
  <li><a href="#options" data-toggle="tab">Options</a></li>
</ul>

<div class="tabbable">
  <div class="tab-content">
    <div class="tab-pane active" id="project">
        <%= f.input :name, label: "Project Name", required: true %>
        <%= f.input :description, as: :text %>
        <%= f.file_field :img_file %>
    </div>


    <div class="tab-pane" id="prod-category">
      <h4>Product Category</h4>
      <%= f.select :product_category_id, ProductCategory.all.map { |r| [r.name, r.id] }, include_blank: true  %>  </br> or </br> 
      <%= link_to 'Create New Category', new_product_category_path %>
    </div>

    <div class="tab-pane" id="palette">
        <%= f.simple_fields_for :palettes do |palette_form| %>
          <%= render 'projects/palette_fields', f: palette_form %>
        <% end %>
    </div>

    <div class="tab-pane" id="attr-layer">
      
    </div>

    <div class="tab-pane" id="options">
      <!-- <div><%= link_to_add_fields "Add Palette", f, :palettes %></div> -->
      <div id="add-attr-layer"></div>
    </br> 
    <%= f.input :show_in_catalog, :as => :boolean, label: "Show in Catalog" %> 
    </div>

    </br>
    <%= f.button :submit, class: "btn btn-primary", id: "create-project" %>


  </div>
</div>

<!-- submit button lies in the tab of palette -->

<% end %>

app/views/projects/_palette_attribute_fields.html.erb
  <div class="form-inputs">
      <%= f.input :name, label: "Attribute Name" %>
      <%= f.file_field :attr_img %>
  </div><br>

app/views/projects/_palette_fields.html.erb
    <div class="tab-pane" id="palette-form">
        <%= f.input :name, label: "Palette Name" %>
    </div>

    <div id="attr-layer-old">
        <%= f.simple_fields_for :attribute_layers do |al_form| %>
            <%= render 'attribute_layer_fields', f: al_form %>
        <% end %>
    </div>



<div id="add-attr-layer-old"><%= link_to_add_fields "Add attribute layer", f, :attribute_layers %></div>

app/views/projects/_product_categories_fields.html.erb
      <h4>Product Category</h4>
      <%= f.select :product_category_id, ProductCategory.all.map { |r| [r.name, r.id] }, include_blank: true  %>  </br> or </br> 
      <%= link_to 'Create New Category', new_product_category_path %>

app/views/projects/artisan_index.html.erb
<h3>Listing Projects</h3>

<table class="table table-bordered table-striped table-hover" id="projects-index" style="width: 1000px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Customer</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.customer %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Design', design_project_path(id: project.id) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<% if current_user.artisan? %> 
<%= link_to 'New Project', new_project_path %>
<% end %>

<style>
table td {
  min-width: 100px;
}

#projects-index {
  width: 600px;
}
</style>

app/views/projects/customer_index.html.erb
<h3>Listing projects</h3>

<table class="table table-bordered table-striped table-hover" id="projects-index" style="width: 1000px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Artisan</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.user.email %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<style>
table td {
  min-width: 100px;
}

#projects-index {
  width: 600px;
}
</style>

app/views/projects/design.html.erb
<div class="row span11 bordered" id="design">
                  
        
    <div id="design-wrapper">  
        <div class="span3" id="pallete">
            <div class="menu bordered">
            <%= select_tag :palette, options_from_collection_for_select(@attribute_layers, :id, :name), include_blank: true, id: 'attr-layer-select' %>

              <% @attributes.each do |attribute| %>
              <%= image_tag attribute.attr_img.url(:thumb), class: "#{attribute.attribute_layer.id} attr" %>
              <% end %>
            </div>
        </div>
    </div>


    <div id="controls">
        <button class="btn btn-primary" style="border: 0 3px 5px 0;" id="prev-version">Prev Version</button>
        <button class="btn btn-primary" style="border: 0 3px 5px 0;" id="next-version">Next Version</button>
        <button class="btn btn-primary" style="border: 3px;" id="remove-img">Remove Image</button>
        <button class="btn btn-primary" style="border: 0 3px 5px 0;" id="restore">Restore</button>
        <button class="btn btn-primary" style="border: 0 3px 5px 0;" id="save">Save</button>
    </div>

<!-- 
            Update Image:
            <%= simple_form_for @project, url_path: projects_path, html: { multipart: true } do |f| %>
                <%= f.file_field :img_file %>
            <% end %>

 -->        

    <div class="span7" id="wrapper_container" style="padding-top: 13px;">
        <div id="tools">
        </div>
        <div class="unselectable" id="canvas_container">
            <canvas id="canvas" width="500" height="500"></canvas>
        </div>
    </div>
</div>    


<script>

console.log("loading projects.js");

var user = "<%= current_user.email %>".split('@')[0];
var user_role = "<%= current_user.role %>"

$(document).ready(function() {

    var contained;

    $("#save").click(function(event) {
        // var dataURL = canvas.toDataURL();
        // document.getElementById("canvas").src = dataURL;
        // console.log("saved! - " + dataURL);
        // console.log(document.getElementById("canvas").src);
        contained =  $("#canvas_container").clone().html();
        var params = { 'design_html' : contained };
        $.ajax({
            type: 'POST',
            url: '/design_versions',
            data: params,
            success: function(data) {
                $("#canvas_container").html("");
                $("#restore").click();
            }
        });
    });


    $("#restore").click(function(event) {
        $.ajax({
            type: 'GET',
            url: '/design_versions/',
            success: function(data) {
                console.log(data);
                $("#canvas_container").html(data);
                var commentboxes = $(".comment-box");
                $.each(commentboxes, function(index, commentbox) {
                    make_textarea_droppable($(commentbox));
                });
                $(".dropped-attr").draggable({'containment': $("#canvas_container") });
                $(".pin").draggable({'containment': $("#canvas_container") });
                $("#save").removeAttr("disabled");
                $("#canvas_container").css({'opacity' : 1});
                $('#canvas').sketch();
            },
            error: function() {
                console.log("error!");
                $('#canvas').sketch();
            }
        });
    });



    $("#prev-version").click(function(event) {
        var params = { 'prev' : true };
        $.ajax({
            type: 'GET',
            url: '/design_versions/',
            data: params,
            success: function(data) {
                $("#canvas_container").html(data);
                var commentboxes = $(".comment-box");
                $.each(commentboxes, function(index, commentbox) {
                    make_textarea_droppable($(commentbox));
                });
                $(".dropped-attr").draggable({'containment': $("#canvas_container") });
                $(".pin").draggable({'containment': $("#canvas_container") });

                $("#save").attr("disabled", "disabled");
                $("#canvas_container").css({'opacity' : .75});
                $('#canvas').sketch();

            }
        });
    });

    $("#next-version").click(function(event) {
        var params = { 'next' : true };
        $.ajax({
            type: 'GET',
            url: '/design_versions/',
            data: params,
            success: function(data) {
                $("#canvas_container").html(data);
                var commentboxes = $(".comment-box");
                $.each(commentboxes, function(index, commentbox) {
                    make_textarea_droppable($(commentbox));
                });
                $(".dropped-attr").draggable({'containment': $("#canvas_container") });
                $(".pin").draggable({'containment': $("#canvas_container") });

                $("#save").attr("disabled", "disabled");
                $("#canvas_container").css({'opacity' : .75});
                $('#canvas').sketch();

            }
        });
    });

// --------------------------------------------------------------------------------------


    $(".attr").draggable({
        helper: "clone"
    });


    $("img").css({ 'opacity' : 0.7, 'zIndex': 10 });


    $("img").data({
        'originalLeft': $("img").css('left'),
        'origionalTop': $("img").css('top')
    });



    $("#canvas_container").on("dblclick", "#canvas", function(event) {
        count = get_count();
        var new_pin = make_new_pin(count);
        $("#canvas_container").append(new_pin);

        var new_commentbox = make_new_comment_box(count);
        $("#canvas_container").append(new_commentbox);
        make_textarea_droppable(new_commentbox);

    });



    $("#canvas_container").on("click", ".close", function(event) {
        var div = $(event.target).closest(".comment-box");
        var id = div.attr("id");
        var pin = $("#"+id);
        pin.remove();
        div.remove();
        count-=1;
    });



    $("#canvas_container").on("keypress", "textarea", function(event) {        
        var code = event.keyCode ? event.keyCode : event.which;
        if (code==13) {
            event.preventDefault();
            var comment_history = $(this).parent().find('.comment-history');
            var comment = $(this).val();

            if (comment.trim()!="") {
                var new_comment_line = $("<span class=comment>" + user + "</span>" + ": " + comment + "<br />");
                new_comment_line.addClass(user_role);
                comment_history.append(new_comment_line);
            }
            $(this).val("").focus();
        }
    });

    $("#canvas_container").on("click", ".minimize", function(event) {
        minimize_obj($(this));
    });

    
    $("#canvas_container").on("click", ".dropped-attr", function(event) {
        var img = $(event.target);
        $(".selected-pin").removeClass("selected-pin");
        img.addClass("selected-pin");
        console.log(img);
    });

    $("#controls").on("click", "#remove-img", function(event) {
        var img = $(".selected-pin");
        if (img.hasClass("pin")) { return false; }
        $(img).remove();
    });
    
    $("#canvas_container").on("click", ".pin", function(event) {


        $(".selected-pin").removeClass("selected-pin");
        var pin = $(event.target);
        pin.addClass("selected-pin");
        pin_id = pin.attr("id");
        var commentboxes = $(".minimize");
        $.each(commentboxes, function(index, commentbox) {
            var commentbox_id = $(commentbox).closest(".comment-box").attr("id");
            if (commentbox_id != pin_id) {
                minimize_obj($(commentbox));
            } else {
                console.log(commentbox_id + "=" + pin_id);
                maximize_obj($(commentbox));
            }
            $("textarea").focus();
        });
    });


    $("#canvas_container").droppable({
        drop: function(event, ui) {
            console.log("droping");
            console.log($(ui.helper));
            if ($(ui.helper).hasClass("pin")) { return false; }
            var image = clone_attr_image($(ui.helper));
            $(this).append(image);
        }
    });


// ------------------------------------------------------------------------------------------------------
    var count = 1;
    var get_count = function() {
        var pins = $(".pin");
        $.each($(".pin"), function(index, pin) {
            var pin_id = parseInt($(pin).attr("id"));
            if ( pin_id >= count ) { count = pin_id+1; }
        });
        return count;
    }


    var make_new_pin = function(count) {
        
        var pin = $('<img/>', {'src': "/defaultpin.png", 'class': "pin", "id": count, "title": count, "data-toggle": "tooltip", "data-placement": "right"} );
        
        pin .css("position", "absolute")
            .css("top",  event.y)
            .css("left", event.x);
        
        pin.draggable({ 
            containment: $("#canvas_container"),
            stop: function(event, ui) {
                $(ui.helper).click();
            }
        });

        return pin;

    }



    var make_new_comment_box = function(count) {

        var minimize = "<span class=minimize>-</span>";
        var maximize = "<span class=maximize>+</span>";
        var close = "<span class=close id=" + count + ">X</span>";
        
        var commentbox = $("<div class=comment-box id=" + count + "><span class=comment-box-header>Comments for Pin " + count + "</span><div class=comment-history></div><textarea class=txt id=" + count + "></textarea>"+ minimize + close + "</div>");
        
        $(commentbox).css("position", "absolute")
                     .css("bottom", 40)
                     .css("right", "60px");

        return commentbox;

    }


    var minimize_obj = function(obj) {
        var div = obj.closest(".comment-box");
        var area = obj.parent().find(".txt");
        $(area).addClass("minimized");
        $(div).hide();
    };


    var maximize_obj = function(obj) {
        var div = obj.closest(".comment-box");
        var area = obj.parent().find(".txt");
        $(area).removeClass("minimized");
        $(div).show();
    };


    var clone_attr_image = function(obj) {

        if (obj.hasClass("dropped-attr")) {
            return obj;
        }

        var image = obj.clone().removeClass("attr").addClass("dropped-attr");
        image.draggable({
            containment: $("#canvas_container")
        });

        return image;
    }

    var make_textarea_droppable = function(commentbox_obj) {

        var textarea = commentbox_obj.find("textarea");

        textarea.droppable({

            over: function(event, ui) { 
                $(ui.helper).addClass("drop-min");
                var img_src = $(ui.helper).attr("src");
                $(this).val("<img class=drop-min src=" + img_src +">");
                $(this).focus();
            },

            out: function(event, ui) {
                $(ui.helper).removeClass("drop-min");
                $(this).val("");
            },

            accept: function(event, ui) {
                return true;
            },

            drop: function(event, ui) {
                $(ui.helper).remove();
                $(this).focus();
            },

            snap: true,

            greedy: true,

            tolerance: "pointer"

        });

    }




    $("#attr-layer-select").on("change", function() {
        var self = $("#attr-layer-select");
        console.log("here");
        console.log(this.options[this.selectedIndex].value);
        var class_val = this.options[this.selectedIndex].value;
        var all_elements = $(".attr");
        console.log(all_elements);
        all_elements.hide();
        var sel_elements = $("."+class_val);
        sel_elements.show();
        console.log(sel_elements);

    });
    $("#attr-layer-select").val(1);

    $("#restore").click();


    var marker_setup = function() {
        $.each(['#f00', '#ff0', '#0f0', '#0ff', '#00f', '#f0f', '#000'], function() {
          $('#tools').append("<a href='#canvas' data-tool=marker data-color='" + this + "' style='width: 10px; background: " + this + ";'>____</a> ");
        });
        $.each(['#fff'], function(){
            $('#tools').append("<a href='#canvas' data-tool=eraser style='width: 10px; background: " + this + ";'>____</a> ");
        });
        $.each([3, 5, 10, 15], function() {
          $('#tools').append("<a href='#canvas' data-size='" + this + "' style='background: #ccc'>" + this + "</a> ");
        });
    }

    marker_setup();

});
  </script>

  <style>
.drop-min {
    height: 40px;
    width: 40px;
}
  </style>



<style>
#canvas {
  background-image: url(<%= @project.img_file.url %>);
  background-repeat:no-repeat;
  background-size: 500px 500px;
}
</style>

app/views/projects/edit.html.erb
<h3>Editing project</h3>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>


<script>
  $(document).ready(function() {
    var attr_layer = $('#attr-layer-old').html();
    $('#attr-layer-old').remove();
    $("#attr-layer").html(attr_layer);

    var add_attr_layer = $('#add-attr-layer-old').html();
    $('#add-attr-layer-old').remove();
    $('#add-attr-layer').html(add_attr_layer);
  });

</script>

app/views/projects/index.html.erb
<h3>Listing projects</h3>

<table class="table table-bordered table-striped table-hover" id="projects-index" style="width: 1000px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

<style>
table td {
  min-width: 100px;
}

#projects-index {
  width: 600px;
}
</style>

app/views/projects/new.html.erb
<h3>New project</h3>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

<script>
  $(document).ready(function() {

  	$("#create-project").hide();

    var attr_layer = $('#attr-layer-old').html();
    $('#attr-layer-old').remove();
    $("#attr-layer").html(attr_layer);

    var add_attr_layer = $('#add-attr-layer-old').html();
    $('#add-attr-layer-old').remove();
    $('#add-attr-layer').html(add_attr_layer);

    $("#_atr_").on("click", function(e) {
    	e.preventDefault();
    	console.log("clicked__");
  		$("#create-project").show();

    });
  });
</script>

app/views/projects/product_by_artisan.html.erb
// Create partial to show catalog @projects is available here..

app/views/projects/product_by_category.html.erb
// Create partial to show catalog @projects is available here..

app/views/projects/products.html.erb
<h3>Listing Products</h3>

<table class="table table-bordered table-striped table-hover" id="projects-index" style="width: 1000px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Product Category</th>
      <th>Description</th>
      <% if current_user.customer? %> <th>Created by</th> <% end %>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.product_category.name %></td>
        <td><%= project.description %></td>
        <% if current_user.customer? %> 
        <td> <%= project.user.email %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Clone Project', duplicate_project_path(id: project.id) %></td>

        <% else %>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Remove from Catalog', show_product_in_catalog_projects_path(id: project.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h4><%=@project.name=%></h4>


</br></br>
<table class="project table table-bordered table-striped table-hover">
    <tr>
        <td>Project Description:</td> <td><%=@project.description=%></td>
    </tr>
    <tr>
        <td>Owner Artisan</td> <td><%=@project.user.email=%>
    </tr>
    <tr>
        <td>Created At:</td> <td><%=@project.created_at=%></td>
    </tr>
    <tr>
        <td>Last Updated At:</td> <td><%=@project.updated_at=%>
    </tr>
    <% if current_user.customer? and @project.customer_id==current_user.id %>
        <tr>
            <td>Actions: </td> <td><%= link_to 'Work on design', design_project_path(id: @project.id) %></td>
        </tr>
        <tr>
            <td></td> <td><%= link_to "Send Invite to artisan" , send_invitation_project_path(@project), method: :post %></td>
        </tr>
    <% elsif @project.customer_id==current_user.id %>
        <tr>
            <td>Actions: </td> <td><%= link_to 'Edit', edit_project_path(@project) %></td>
        </tr>
        <tr>
            <td></td> <td><%= link_to 'Design', design_project_path(id: @project.id) %></td>
        </tr>   
    <% end %>
</table>


</br>

<% if current_user.artisan? %>

<h4>Palettes associated with this Project</h4>

<table class="project table table-bordered table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Link</th>
  <% @palettes.each do |palette| %>
    <tr>
      <td><%= palette.name %></td>
      <td><%= link_to 'Show', palette %></td>
    </tr>
  <% end %>
</table>
<% end %>



<div id="canvas_container">
    <div id="canvas"></div>
</div>

<style>
#canvas {
  background-image: url(<%= @project.img_file.url %>);
  background-repeat:no-repeat;
  width: 500px;
  height: 500px;
  background-size: 500px 500px;
}
</style>

// <script>
//     var id = <%= @project.id %>
//     $(document).ready(function() {
//         var params = { 'id' : id };
//         $.ajax({
//             type: 'GET',
//             url: '/design_versions/',
//             data: params,
//             success: function(data) {
//                 console.log(data);
//                 $("#canvas_container").html(data);
//             }
//         });
//     });
// </script>