config/routes.rb
Artisania::Application.routes.draw do

  root :to => "projects#index"

  resources :palettes do
    member do
      get :alt_show
    end
  end
  
  resources :attribute_layers
  resources :attributes
  resources :design_versions
  resources :product_categories
  resources :catalogs

  devise_for :users

  resources :projects do
    member do
      get  :design
      post :send_invitation
      get  :duplicate
    end
    collection do
      get :products_by_category
      get :products_by_artisan
      get :products
      get :customer_projects
      get :show_product_in_catalog

    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artisania</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
	  <div class="navbar-inner">
		  <%= link_to 'Artisania', root_path, class: 'brand' %>
	    <ul class="nav">
			<% if current_user %>
				<% if current_user.artisan? %>
					<li><%= link_to 'Projects',  projects_path %></li>
					<li><%= link_to 'Catalog', 	 products_by_artisan_projects_path(user_id: current_user.id) %></li>
					<li><%= link_to 'Palettes',  palettes_path %></li>
				<% elsif current_user.customer? %>
					<li><%= link_to 'Projects',  projects_path(customer_id: current_user.id) %></li>
					<li><%= link_to 'Catalogs', catalogs_path %></li>
					<li><%= link_to 'Products', products_projects_path %></li>
				<% end %>
	    	<% end %>
	    </ul>
			<ul class="nav pull-right" style="float: right;">
				<% if current_user %>
					<li style="color: white;"><a href="">Hello, <%= current_user.email %></a></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
					<li><%= link_to "Forgot password?", new_password_path(resource_name) %></li>
					<% if request.fullpath == new_registration_path(resource_name) %>
						<li><%= link_to "Sign in", new_session_path(resource_name) %></li>
					<% else %>
						<li><%= link_to 'Sign Up', new_user_registration_path %></li>
					<% end %>
				<% end %>
			</ul>
	  </div>
	</div>
    <div class="row" id="main-container">
        <div class="span0" id="left-main-container">
        </div>
        <div class="span12" id="right-main-container">
        	<%= yield %>
        </div>
    </div>
</body>
</html>

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"

  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

body

  == yield

  = javascript_include_tag "application"